api/blueprints/answering_quiz.py
"""
This Blueprint is used to define which routes to use when answering
a quiz. The only common argument given to these routes is the quiz_id
as other required information is handled on the backend. All routes
in this blueprint should only be accessed from the quiziverse UI.The
routes in this Blueprint include: quizinfo, take, skip, previous,
submitanswer, quit and finishquiz.
"""

import json
from api.config import year
from datetime import datetime, timezone, timedelta
from flask import Blueprint, flash, request, session
from flask import render_template, url_for, redirect
from flask_login import current_user
from models.result import Result
from models.quiz import Quiz


taking_bp = Blueprint('taking', __name__)


@taking_bp.route('/quizinfo/<quiz_id>', methods=['GET'])
def quizinfo(quiz_id):
    """
    Retrieves information about a quiz before it is taken.

    Args:
        quiz_id(str): Unique identifier of a quiz.

    Response:
        HTML page containing quiz information like
        its decription and number of questions.

    Example Usage:
        GET /quizinfo/34ed5fc9-5ffd-4696-b71f-21264162b87c
    """
    if not current_user.is_authenticated:
        flash("You must be logged in first")
        return redirect(url_for('auth.login'))
    quiz = Quiz.get(quiz_id)
    if not quiz:
        flash("Quiz not found")
        return redirect(request.referrer)
    return render_template(
        'quizinfo.html', title=quiz['title'], year=year, quiz=quiz
    )


@taking_bp.route('/take/<quiz_id>', methods=['GET'])
def takequiz(quiz_id):
    """
    Allows user to take a quiz. Initialises a server side session containg
    information the quiz being taken. The session is created if it does not
    exist and is used for maintaining user state between requests.

    Args:
        quiz_id(str): Unique identifier of a quiz.

    Response:
        HTML page containing a UI for answering questions.

    Example Usage:
        GET /take/34ed5fc9-5ffd-4696-b71f-21264162b87c
    """
    if not current_user.is_authenticated:
        flash("You must be logged in first")
        return redirect(url_for('auth.login'))

    quiz = Quiz.get(quiz_id)
    if quiz is None:
        flash("Quiz not found")
        return redirect(request.referrer)

    if "taking_quiz" not in session:
        start_time = datetime.now(timezone.utc)
        finish_time = start_time + timedelta(seconds=quiz["time_limit"])
        # This should cache without calling session.modified = True
        session["taking_quiz"] = {
            "quiz_id": quiz_id,
            "current_index": 0,
            "previous_index": None,
            "answers": {},
            "timeout": False,
            "finished": False,
            "start_time": start_time,
            "current_time": start_time,
            "finish_time": finish_time,
            "duration": finish_time - start_time
        }
        del start_time
        del finish_time

    # Potentially useless
    if session["taking_quiz"]["quiz_id"] != quiz_id:
        flash("Use interface to take the quiz")
        del session["taking_quiz"]
        return redirect(url_for('dash.home'))

    start_time = session["taking_quiz"]["start_time"]
    session["taking_quiz"]["duration"] = \
        session["taking_quiz"]["finish_time"] - \
        session["taking_quiz"]["current_time"]
    session.modified = True

    return render_template(
        'takequiz.html',
        title=quiz["title"],
        year=year,
        question=quiz['questions'][session["taking_quiz"]["current_index"]],
        start_time=start_time,
        duration=int((session["taking_quiz"]["duration"]).total_seconds())
    )


@taking_bp.route('/skip/<quiz_id>', methods=["POST"])
def skip(quiz_id):
    """
    Skips a question in a quiz. Assigns None as the answer to the current
    question, increments the index of the current index in session object
    and redirects to takequiz route.

    Args:
        quiz_id(str): Unique identifier of a quiz.

    Response:
        Redirect to /take route with current quiz_id.

    Example Usage:
        GET /skip/34ed5fc9-5ffd-4696-b71f-21264162b87c
    """
    if not current_user.is_authenticated:
        flash("You must be logged in first")
        return redirect(url_for('auth.login'))

    if "taking_quiz" not in session:
        flash("You are not taking a quiz")
        return redirect(url_for('dash.home'))

    session["taking_quiz"]["current_time"] = datetime.now(timezone.utc)

    quiz = Quiz.get(quiz_id)
    if quiz is None:
        del session["taking_quiz"]
        flash("Quiz not found")
        return redirect(url_for('dash.home'))

    if session["taking_quiz"]["current_time"] > \
            session["taking_quiz"]["finish_time"]:
        session["taking_quiz"]["timeout"] = True
        flash("Time Ran Out")
        return redirect(url_for('taking.finishquiz', quiz_id=quiz_id))

    if session["taking_quiz"]["current_index"] == (len(quiz["questions"]) - 1):
        session["taking_quiz"]["finished"] = True
        return redirect(url_for('taking.finishquiz', quiz_id=quiz_id))

    payload = request.form.get('answer')
    if not payload:
        print("No data recied when submitting quiz")
        return redirect(request.referrer)

    try:
        payload = json.loads(payload)
    except json.JSONDecodeError:
        # TODO use log module to track such unexpected errors
        del session["taking_quiz"]
        flash("Invalid data submitted")
        return redirect(request.referrer)

    question_id, answer = list(payload['answer'].items())[0]
    del payload
    key = session["taking_quiz"]["current_index"]
    if question_id != quiz["questions"][key]["question_id"]:
        del key
        del session["taking_quiz"]
        flash("Tampering detected")
        return redirect(url_for('dash.home'))

    # answer = uuid4()
    answer = None
    session["taking_quiz"]["answers"][question_id] = {
        "question_id": question_id,
        "answer": answer
    }

    session["taking_quiz"]["previous_index"] = \
        session["taking_quiz"]["current_index"]
    session["taking_quiz"]["current_index"] += 1
    session.modified = True

    return redirect(url_for('taking.takequiz', quiz_id=quiz_id))


@taking_bp.route('/previous/<quiz_id>', methods=['POST'])
def previous(quiz_id):
    """
    Allows users to go backward in quiz and answer skipped questions.
    Decrements the current index in the session and redirects to take
    route with current quiz_id.
    
    Args:
        quiz_id(str): Unique identifier of a quiz.

    Response:
        Redirect to /take route with current quiz_id.

    Example Usage:
        GET /previous/34ed5fc9-5ffd-4696-b71f-21264162b87c
    """
    if not current_user.is_authenticated:
        flash("You must be logged in first")
        return redirect(url_for('auth.login'))

    if "taking_quiz" not in session:
        flash("You are not taking a quiz")
        return redirect(url_for('dash.home'))

    session["taking_quiz"]["current_time"] = datetime.now(timezone.utc)

    quiz = Quiz.get(quiz_id)
    if not quiz:
        del session["taking_quiz"]
        flash("Quiz not found")
        return redirect(url_for('dash.home'))

    if session["taking_quiz"]["current_time"] > \
            session["taking_quiz"]["finish_time"]:
        session["taking_quiz"]["timeout"] = True
        flash("Time Ran Out")
        return redirect(url_for('taking.finishquiz', quiz_id=quiz_id))

    payload = request.form.get('answer')
    if not payload:
        print("No data recied when submitting quiz")
        return redirect(request.referrer)

    try:
        payload = json.loads(payload)
    except json.JSONDecodeError:
        del session["taking_quiz"]
        flash("Invalid data submitted")
        return redirect(request.referrer)

    question_id, answer = list(payload['answer'].items())[0]
    del payload
    del answer
    key = session["taking_quiz"]["current_index"]
    if question_id != quiz["questions"][key]["question_id"]:
        del key
        del session["taking_quiz"]
        flash("Tampering detected")
        return redirect(url_for('dash.home'))

    # Store answer
    if session["taking_quiz"]["current_index"] == 0:
        flash("No previous question to do back to")
        return redirect(url_for('taking.takequiz', quiz_id=quiz_id))

    session["taking_quiz"]["previous_index"] = \
        session["taking_quiz"]["current_index"] - 1
    session["taking_quiz"]["current_index"] = \
        session["taking_quiz"]["previous_index"]
    session.modified = True
    return redirect(url_for('taking.takequiz', quiz_id=quiz_id))


@taking_bp.route('/submitanswer/<quiz_id>', methods=["POST"])
def submitanswer(quiz_id):
    """
    Allows Submittion of question answers. Saves the answer for the current
    question in the session object and increments the current index.

    Args:
        quiz_id(str): Unique identifier of a quiz.

    Response:
        Redirect to /take route with current quiz_id.

    Example Usage:
        GET /submitanswer/34ed5fc9-5ffd-4696-b71f-21264162b87c
    """
    if not current_user.is_authenticated:
        flash("You must be logged in first")
        return redirect(url_for('auth.login'))

    if "taking_quiz" not in session:
        flash("You are not taking a quiz")
        return redirect(url_for('dash.home'))

    session["taking_quiz"]["current_time"] = datetime.now(timezone.utc)

    quiz = Quiz.get(quiz_id)
    if not quiz:
        del session["taking_quiz"]
        flash("Quiz not found")
        return redirect(url_for('dash.home'))

    if session["taking_quiz"]["current_time"] > \
            session["taking_quiz"]["finish_time"]:
        session["taking_quiz"]["timeout"] = True
        flash("Time Ran Out")
        return redirect(url_for('taking.finishquiz', quiz_id=quiz_id))

    payload = request.form.get('answer')
    if not payload:
        print("No data recied when submitting quiz")

api/blueprints/information.py
"""
Defines Blueprint for routes that presents simple information to
the user, including: index, about and accout routes.
"""

from flask import flash, render_template, url_for, redirect
from flask_login import current_user
from models.user import User
from flask import Blueprint, render_template
from api.config import year


info_bp = Blueprint('info', __name__)


@info_bp.route("/", methods=["GET", "POST"])
def index():
    """ 
    Retrieves the index page where the product information
    is displayed.

    Response:
        HTML page for the index page.
    """
    return render_template("index.html", title="QUIZIVERSE", year=year)


@info_bp.route("/about", methods=["GET"])
def about():
    """
    Retrieves the about page where the infomation about the developer is
    displayed.

    Response:
        HTML page for the about page.
    """
    return render_template("about.html", title="ABOUT", year=year)


@info_bp.route("/account", methods=["GET", "POST"])
def account():
    """
    Retrieves the users account information including all actions they
    can do to their account.
    """
    if not current_user.is_authenticated:
        flash("You are are not logged in")
        return redirect(url_for('dash.home'))

    user = User.getByID(current_user.get_id())

    return render_template(
        "account.html",
        title="PROFILE",
        year=year, user=user
    )

api/blueprints/quiz_routes.py
"""
The Blueprint for routes used when creating, editing and deleting
quizzes including routes for: create, edit and delete.
"""

import json
from api.config import year, domain
from flask import Blueprint, flash, request, session
from flask import render_template, url_for, redirect
from flask_login import current_user
from models.quiz import Quiz
from urllib.parse import urlparse
from pprint import pprint


quiz_bp = Blueprint('quiz', __name__)


@quiz_bp.route("/create", methods=["GET", "POST"])
def create():
    """
    Allows a user to create a quiz using a form page that is rendered on a get
    request.

    Response:
        HTML page created with the create.html template.
    """
    if not current_user.is_authenticated:
        flash("You must be logged in first")
        return redirect(url_for('auth.login'))

    if request.method == "POST":
        data = request.form.get("quiz_json", '')
        pprint(data)
        data = json.loads(data)

        if data['time_limit'] is None:
            data['time_limit'] = 0

        validation = Quiz.validateFields(
            title=data['title'],
            description=data['description'],
            time_limit=data['time_limit'],
            category=data['category'],
        )
        if validation[0]:
            pass
        else:
            flash(validation[1])
            return render_template(
                "create.html", title='quiz.create',
                year=year, data=data
            )

        for question in data["questions"]:
            validation = Quiz.validateQuestion(question)
            if validation[0]:
                pass
            else:
                flash(validation[1])
                return render_template(
                    "create.html", title='quiz.create',
                    year=year, data=data
                )

        quiz = Quiz(
            title=data['title'],
            creator_id=current_user.get_id(),
            description=data['description'],
            time_limit=data['time_limit']
        )
        quiz.addMultipleQuestions(data['questions'])
        pprint(quiz.__dict__)
        quiz.save()
        flash("Quiz created successfully")
        return redirect(url_for('dash.home'))

    return render_template("create.html", title='quiz.create', year=year)


@quiz_bp.route('/edit/<quiz_id>', methods=['GET', 'POST'])
def edit(quiz_id):
    """
    Allows a user to edit a quiz with a given quiz_id using a form page
    that is rendered on a get request.

    Args:
        quiz_id(str): Unique identifier of a quiz.

    Response:
        HTML page created with the create.html template.
    """
    if not current_user.is_authenticated:
        return redirect(url_for('auth.login'))

    quiz = Quiz.get(quiz_id)
    if not quiz:
        flash("Invalid quiz id")
        return redirect(url_for('dash.home'))
    if not quiz['creator_id'] == current_user.get_id():
        flash("Not authorized to edit this quiz")
        return redirect(url_for('dash.home'))

    if request.method == "POST":
        data = request.form.get("quiz_json", '')

        session['edit_quiz_data'] = data

        try:
            data = json.loads(data)
        except json.JSONDecodeError:
            flash("Invalid quiz data")
            return redirect(url_for('quiz.edit', quiz_id=quiz_id))

        if data['time_limit'] is None:
            data['time_limit'] = 0
        pprint(data)

        validation = Quiz.validateFields(
            title=data['title'],
            description=data['description'],
            category=data['category'],
            time_limit=data['time_limit'],
        )
        if validation[0]:
            pass
        else:
            flash(validation[1])
            return redirect(url_for('quiz.edit', quiz_id=quiz_id))

        for question in data["questions"]:
            validation = Quiz.validateQuestion(question)
            if validation[0]:
                pass
            else:
                session['edit_quiz_data'] = data
                flash(validation[1])
                return redirect(url_for('quiz.edit', quiz_id=quiz_id))

        try:
            Quiz.update(quiz_id, data)
            del session['edit_quiz_data']
            flash("Quiz updated successfully")
        except KeyError as e:
            print(e)
            flash("Quiz update failed")
        return redirect(url_for('dash.home'))

    try:
        data = session["edit_quiz_data"]
    except KeyError:
        data = None
        pass
    url = urlparse(request.referrer)
    if (url.netloc == '127.0.0.1:5000' or url.netloc == domain) \
            and url.path == f'/edit/{quiz_id}' and data:
        data['quiz_id'] = quiz_id
        return render_template(
            "edit.html", title='quiz.edit',
            year=year, data=data
        )

    return render_template(
        "edit.html", title='quiz.edit',
        year=year, data=quiz
    )


@quiz_bp.route('/delete/<quiz_id>', methods=['GET'])
def delete(quiz_id):
    """
    Allows a user to delete a quiz with a given quiz_id.

    Args:
        quiz_id(str): Unique identifier of a quiz.

    Response:
        Redirect to the page there the operation was started.
    """
    if not current_user.is_authenticated:
        flash("You must be logged in first")
        return redirect(url_for('auth.login'))

    quiz = Quiz.get(quiz_id)
    if not quiz:
        flash("Quiz not found")
        return redirect(request.referrer)

    if not quiz['creator_id'] == current_user.get_id():
        flash("You are not authorized to delete this quiz")
        return redirect(url_for('dash.home'))

    try:
        Quiz.delete(quiz_id)
        flash("Quiz deleted successfully")
        return redirect(request.referrer)
    except KeyError as e:
        print(e)
        flash("Quiz deletion failed")
    return redirect(request.referrer)

api/templates/_topnavigation.html
<a href="{{ url_for('info.index') }}" class="logo">QUIZIVERSE</a>
<nav>
  <a href="{{ url_for('dash.home') }}">Home</a>
  <a href="{{ url_for('info.account') }}">Account</a>
  <a href="{{ url_for('auth.logout') }}">Logout</a>
</nav>

api/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{{ title }}{% endblock title %}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/footer.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
    {% block CSS %}
    {% endblock CSS %}
  </head>
  <body>
    {% block header %}
    <header class="base-header">
      <a href="{{ url_for('info.index') }}" class="logo">QUIZIVERSE</a>
      <nav>
        <a href="{{ url_for('dash.home') }}">Home</a>
        <a href="{{ url_for('info.about') }}">About</a>
        <a href="{{ url_for('auth.login') }}">Login</a>
      </nav>
    </header>
    {% endblock header %}
    {% block main %}
    <main class="base-main">
      {% with messages = get_flashed_messages() %}
        {% if messages %}
          <ul>
            {% for message in messages %}
              <li>{{ message }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      {% endwith %}
      <div class="hero">
        {% with messages = get_flashed_messages() %}
          {% if messages %}
            <ul>
              {% for message in messages %}
                <li>{{ message }}</li>
              {% endfor %}
            </ul>
          {% endif %}
        {% endwith %}
        <h1>Welcome to QUIZIVERSE</h1>
        <p>Start your journey into a universe of quizzes.</b></p>
        <a href="{{ url_for('auth.login') }}"><button class="get-started-btn">Get Started</button></a>
      </div>
      <section class="features">
        <div class="feature">
          <h2>Quiz Creation</h2>
          <p>We offer a feature set that allows users to create and edit quizzes seamlessly.</p>
          <!-- <p>If your are not happy with some of the questions the scoring of the time limits you can always edit them letter</p> -->
        </div>
        <div class="feature">
          <h2>Streamlined UI</h2>
          <p>Our UI offers a user experience that makes it easy to answer quizzes and view your results.</p>
          <!-- <p>All your results for all the quizzes you take will be stored and you can access them at any time in your results page.</p> -->
        </div>
        <div class="feature">
          <h2>Quiz API</h2>
          <p>All quizzes on quiziverse are exposed through a RESTful API for you to use in your own applications.</p>
          <!-- <p>Find a quiz you like? Well you can simply copy its id and use our api to get the quiz for yourself.</p> -->
        </div>
      </section>
    </main>
    {% endblock main %}
    <footer>
      <div>
        <p>&copy; {{ year }} QUIZIVERSE. All rights reserved.</p>
      </div>
    </footer>
  </body>
</html>

api/templates/finishquiz.html
{% extends 'home.html' %}

{% block childcss %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/finish.css') }}">
{% endblock childcss %}

{% block main %}
{% include "_verticalnav.html" %}
<div>
{% with messages = get_flashed_messages() %}
  {% if messages %}
    <ul>
      {% for message in messages %}
        <li>{{ message }}</li>
      {% endfor %}
    </ul>
  {% endif %}
{% endwith %}
<main class="main-section">
  <div class="quiz-results-container">
    <h2 class="results-title">{{ title }} Results</h2>
    
    <div class="results-summary">
      <p>Your total score is: <strong>{{ user_score }}</strong></p>
      <p>Percentage: <strong>{{ percentage_score }}&#37;</strong></p>
      <p>Maximum score: <strong>{{ max_score }}</strong></p>
      <p>Accuracy: <strong>{{ accuracy }}&#37;</strong></p>
      <p>Correct Questions: <strong>{{ correct_answers }}</strong></p>
      <p>Questions Attempted: <strong>{{ questions_attempted }}</strong></p>
    </div>
    
    <div class="results-actions">
      <a href="{{ url_for('dash.home') }}" class="button return-home">Return Home</a>
      <a href="{{ url_for('taking.quizinfo', quiz_id=quiz_id) }}" class="button retry-quiz">Retry</a>
    </div>
  </div>
</main>

{% endblock main %}

api/templates/home.html
{% extends "base.html" %}

{% block CSS %}
 <link rel="stylesheet" href="{{ url_for('static', filename='css/home.css') }}">
{% block childcss %}
{% endblock childcss %}
{% endblock CSS %}

{% block header %}
<header class="home-header">
  {% include "_topnavigation.html" %}
</header>
{% endblock header %}

{% block main %}
<section class="page-container">
{% include "_verticalnav.html" %}
<main class="main-section">

  <section class="filter-section">
    <div class="filter-search-bar">
      <form method="GET" action="{{ url_for('dash.home') }}">
        <div class="filter">
          {% if selected_category %}
            <input type="hidden" name="page" value="1">
          {% endif %}
          <label for="category">Order By:</label>
          <select name="category" id="category">
            <option value="">Default (Title)</option>
            {% for category in categories %}
              <option value="{{ category }}" {% if category == selected_category %}selected{% endif %}>{{ category }}</option>
            {% endfor %}
          </select>
        </div>
        <div class="search">
          <label for="search">Search:<input type="text" name="search" id="search" placeholder="Search by title..." value="{{ query }}"></label>
          <div class="filter-search-btns">
            <button type="submit" name="action" value="filter">Filter</button>
            <button type="submit" name="action" value="search">Search</button>
          </div>
        </div>
      </form>
    </div>
  </section>
    <div>
    {% with messages = get_flashed_messages() %}
      {% if messages %}
        <ul>
          {% for message in messages %}
            <li>{{ message }}</li>
          {% endfor %}
        </ul>
      {% endif %}
    {% endwith %}
    </div>
    <div class="quiz-card-container">
      {% if query %}
        {% if quizzes %}
        {% for quiz in quizzes %}
          <div class="quiz-card">
            <h3 class="quiz-title">{{ quiz.title }}</h3>
            <p class="quiz-description">{{ quiz.description }}</p>
            <p class="quiz-meta">Questions: {{ quiz.questions|length }}</p>
            <p class="quiz-meta">Time Limit: {{ quiz.time_limit if quiz.time_limit > 0 else 'No Time Limit' }}</p>
            <div class="card-footing">
              <a href="{{ url_for('taking.quizinfo', quiz_id=quiz.quiz_id) }}"><button class="take-quiz-btn">Take Quiz</button></a>
              <a href=""><button class="copy-id-btn" data-quizid={{ quiz.quiz_id }}>Copy ID</button></a>
            </div>
        </div>
        {% endfor %}
        {% else %}
          <h3>Not Found</h3>
        {% endif %}
      {% else %}
        {% if quizzes %}
          {% for quiz in quizzes %}
            <div class="quiz-card">
              <h3 class="quiz-title">{{ quiz.title }}</h3>
              <p class="quiz-description">{{ quiz.description }}</p>
              <p class="quiz-meta">Questions: {{ quiz.questions|length }}</p>
              <p class="quiz-meta">Time Limit: {{ quiz.time_limit if quiz.time_limit > 0 else 'No Time Limit' }}</p>
              <div class="card-footing">
                <a href="{{ url_for('taking.quizinfo', quiz_id=quiz.quiz_id) }}"><button class="take-quiz-btn">Take Quiz</button></a>
                <a href=""><button class="copy-id-btn" data-quizid={{ quiz.quiz_id }}>Copy ID</button></a>
              </div>
            </div>
          {% endfor %}
        {% else %}
          <p>We have no quizzes at the moment</p>
        {% endif %}
      {% endif %}
    </div>
      <div class="pagination">
        {% if pagination.has_prev %}
          <a href="{{ pagination.prev_url }}"><button>&laquo; Previous</button></a>
        {% else %}
          <span class="disabled">&laquo; Previous</span>
        {% endif %}
        
        <span>Page {{ pagination.page }} of {{ pagination.total_pages }}</span>
        
        {% if pagination.has_next %}
          <a href="{{ pagination.next_url }}"><button>Next &raquo;</button></a>
        {% else %}
          <span class="disabled">Next &raquo;</span>
        {% endif %}
      </div>
</main>
<script src="{{ url_for('static', filename='js/home.js') }}"></script>
</section>
{% endblock main %}

api/templates/index.html
{% extends "base.html" %}

api/templates/myquizzes.html
{% extends "base.html" %}

{% block CSS %}
 <link rel="stylesheet" href="{{ url_for('static', filename='css/home.css') }}">
{% block childcss %}
{% endblock childcss %}
{% endblock CSS %}

{% block header %}
<header class="home-header">
  {% include "_topnavigation.html" %}
</header>
{% endblock header %}

{% block main %}
<section class="page-container">
{% include "_verticalnav.html" %}
<main class="main-section">

  <section class="filter-section">
    <div class="filter-search-bar">
      <form method="GET" action="{{ url_for('dash.myquizzes') }}">
        <div class="filter">
          {% if selected_category %}
            <input type="hidden" name="page" value="1">
          {% endif %}
          <label for="category">Order By:</label>
          <select name="category" id="category">
            <option value="">Default (Title)</option>
            {% for category in categories %}
              <option value="{{ category }}" {% if category == selected_category %}selected{% endif %}>{{ category }}</option>
            {% endfor %}
          </select>
        </div>
        <div class="search">
          <label for="search">Search:<input type="text" name="search" id="search" placeholder="Search by title..." value="{{ query }}"></label>
          <div class="filter-search-btns">
            <button type="submit" name="action" value="filter">Filter</button>
            <button type="submit" name="action" value="search">Search</button>
          </div>
        </div>
      </form>
    </div>
  </section>
    <div>
    {% with messages = get_flashed_messages() %}
      {% if messages %}
        <ul>
          {% for message in messages %}
            <li>{{ message }}</li>
          {% endfor %}
        </ul>
      {% endif %}
    {% endwith %}
    </div>
    <div class="quiz-card-container">
      {% if query %}
        {% if quizzes %}
        {% for quiz in quizzes %}
          <div class="quiz-card">
            <h3 class="quiz-title">{{ quiz.title }}</h3>
            <p class="quiz-description">{{ quiz.description }}</p>
            <p class="quiz-meta">Questions: {{ quiz.questions|length }}</p>
            <p class="quiz-meta">Time Limit: {{ quiz.time_limit if quiz.time_limit > 0 else 'No Time Limit' }}</p>
            <div class="card-footing">
              <a href="{{ url_for('quiz.edit', quiz_id=quiz.quiz_id) }}"><button class="take-quiz-btn">Edit</button></a>
              <a href=""><button class="copy-id-btn" data-quizid={{ quiz.quiz_id }}>Copy ID</button></a>
              <a href="{{ url_for('quiz.delete', quiz_id=quiz.quiz_id) }}"><button class="delete-btn">Delete</button></a>
            </div>
        </div>
        {% endfor %}
        {% else %}
          <h3>Not Found</h3>
        {% endif %}
      {% else %}
        {% if quizzes %}
          {% for quiz in quizzes %}
            <div class="quiz-card">
              <h3 class="quiz-title">{{ quiz.title }}</h3>
              <p class="quiz-description">{{ quiz.description }}</p>
              <p class="quiz-meta">Questions: {{ quiz.questions|length }}</p>
              <p class="quiz-meta">Time Limit: {{ quiz.time_limit if quiz.time_limit > 0 else 'No Time Limit' }}</p>
              <div class="card-footing">
                <a href="{{ url_for('quiz.edit', quiz_id=quiz.quiz_id) }}"><button class="take-quiz-btn">Edit</button></a>
                <a href=""><button class="copy-id-btn" data-quizid={{ quiz.quiz_id }}>Copy ID</button></a>
                <a href="{{ url_for('quiz.delete', quiz_id=quiz.quiz_id) }}"><button class="delete-btn">Delete</button></a>
              </div>
            </div>
          {% endfor %}
        {% else %}
          <p>You have not created any quizzes yet.</p>
        {% endif %}
      {% endif %}
    </div>
      <div class="pagination">
        {% if pagination.has_prev %}
          <a href="{{ pagination.prev_url }}"><button>&laquo; Previous</button></a>
        {% else %}
          <span class="disabled">&laquo; Previous</span>
        {% endif %}
        
        <span>Page {{ pagination.page }} of {{ pagination.total_pages }}</span>
        
        {% if pagination.has_next %}
          <a href="{{ pagination.next_url }}"><button>Next &raquo;</button></a>
        {% else %}
          <span class="disabled">Next &raquo;</span>
        {% endif %}
      </div>
</main>
<script src="{{ url_for('static', filename='js/home.js') }}"></script>
</section>
{% endblock main %}